
prometheus_web_external_url: "https://prometheus.ucoder.ir"
prometheus_storage_retention: "7d"
prometheus_targets:
  node:
    - targets:
        - "srv7.ucoder.ir:9100"
        - "srv8.ucoder.ir:9100"
  grafana:
    - targets:
      - "grafana.ucoder.ir:3000"
  nginx:
    - targets:
      - "srv8.ucoder.ir:9113"
prometheus_scrape_configs:
- job_name: "prometheus"
  metrics_path: "/metrics"
  static_configs:
  - targets:
    - "0.0.0.0:9090"
- job_name: "nginx"
  file_sd_configs:
  - files:
    - "/etc/prometheus/file_sd/nginx.yml"
- job_name: "node"
  file_sd_configs:
  - files:
    - "/etc/prometheus/file_sd/node.yml"
- job_name: "grafana"
  file_sd_configs:
  - files:
    - "/etc/prometheus/file_sd/grafana.yml"
