- name: "Installing Good Packages"
  apt: pkg={{ item }} state=latest
  with_items:
  - git
  - vim
  - nano
  - ansible
  - w3m

- name: "Enable git credential store"
  shell: git config --global credential.helper store

- name: set vim as default editor
  command: update-alternatives --set editor /usr/bin/vim.basic