export FIREFOX_MEMORY_LIMIT="1490m"
export FIREFOX_SHM_LIMIT="200m"
export VIM_MEMORY_LIMIT="550m"
export VIM_SHM_LIMIT="10m"
export LINUX_MEMORY_LIMIT="50m"
export LINUX_SHM_LIMIT="10m"
export GLASSFISH_MEMORY_LIMIT="660m"
export GLASSFISH_SHM_LIMIT="30m"
export NAUTILUS_MEMORY_LIMIT="150m"
export NAUTILUS_SHM_LIMIT="70m"
export BASH_MEMORY_LIMIT="270m"
export BASH_SHM_LIMIT="10m"

export OS_MEMORY_LIMIT="436m"
export OS_SHM_LIMIT="64m"

# Total: 4000m
# Os: 500m
# Idle: 0m
