grafana_security:
  admin_user: admin
  admin_password: "{{ vault_grafana_password }}"
grafana_auth:
  anonymous:
    org_name: "Main Org."
    org_role: Viewer
grafana_datasources:
  - name: "Prometheus"
    type: "prometheus"
    access: "proxy"
    url: "http://prometheus.ucoder.ir:9090"
    isDefault: true
grafana_dashboards:
  - dashboard_id: '1860'
    revision_id: '12'
    datasource: '{{ grafana_datasources.0.name }}'
  - dashboard_id: '3662'
    revision_id: '2'
    datasource: '{{ grafana_datasources.0.name }}'
  - dashboard_id: '4271'
    revision_id: '4'
    datasource: '{{ grafana_datasources.0.name }}'
  - dashboard_id: '462'
    revision_id: '1'
    datasource: '{{ grafana_datasources.0.name }}'
