- name: start_nginx
  service: name=nginx state=started enabled=yes

- name: reload_nginx
  service: name=nginx state=reloaded

- name: restart_nginx
  service: name=nginx state=restarted

- name: redeploy
  include: redeploy.yml

- name: reload_sniproxy
  service: name=sniproxy state=restarted
