- name: start_nginx
  service: name=nginx state=started enabled=yes

- name: reload_nginx
  service: name=nginx state=reloaded

- name: restart_nginx
  service: name=nginx state=restarted

- name: reload_sniproxy
  service: name=sniproxy state=restarted

- name: start_shellinabox
  service: name=shellinabox state=started enabled=yes

- name: restart_shellinabox
  service: name=shellinabox state=restarted