- name: Deploy node_exporter
  hosts: all
  become: true
  roles:
    - cloudalchemy.node-exporter
    - post-nodeexporter

- hosts: prometheus
  name: Deploy prometheus
  become: true
  roles:
  - cloudalchemy.prometheus
  - post-prometheus

- name: Deploy grafana
  become: true
  hosts: grafana
  roles:
    - cloudalchemy.grafana
    - post-grafana
