- hosts: all
  roles:
    - nginx_certbot
    - nginx_revproxy
  become: true
  vars:
    nginx_certbot_domains:
      prometheus.ucoder.ir:
        domains:
        - prometheus.ucoder.ir
        letsencrypt_email: info@ucoder.ir

      grafana.ucoder.ir:
        domains:
        - grafana.ucoder.ir
        letsencrypt_email: info@ucoder.ir

    nginx_revproxy_sites:
      prometheus.ucoder.ir:
        domains:
          - prometheus.ucoder.ir
        upstreams:
          - { backend_address: 127.0.0.1, backend_port: 9090 }
        ssl: true
        letsencrypt: true

      grafana.ucoder.ir:
        domains:
          - grafana.ucoder.ir
        upstreams:
          - { backend_address: 127.0.0.1, backend_port: 3000 }
        ssl: true
        letsencrypt: true