- name: Install python-passlib for Python 3 hosts
  apt:
    name:
        - "python3-passlib"
    state: present
  when:
    - ansible_python['version']['major'] == 3

- name: Install python-passlib for Python 2 hosts
  apt:
    name:
        - "python-passlib"
    state: present
  when:
    - ansible_python['version']['major'] == 2

- name: "Creating htpasswd file"
  htpasswd:
    path: /etc/nginx/conf.d/{{ shellinabox_domain }}.htpasswd
    name: "{{ shellinabox_username }}"
    password: "{{ shellinabox_password }}"
    owner: root
    group: root
    mode: 0644

- name: installing shellinabox
  apt:
    name: shellinabox
    state: present
  notify: start_shellinabox

- name: updating shellinabox
  apt:
    name: shellinabox
    state: latest
  notify: restart_shellinabox

- name: "Installing nginx"
  apt: pkg={{ item }} state=present
  with_items:
  - nginx
  notify:
    - start_nginx

- name: "Update nginx"
  apt: pkg={{ item }} state=latest
  with_items:
  - nginx
  notify:
    - restart_nginx

- name: Update Site Config
  template:
    src=shellinabox.conf.j2
    dest=/etc/nginx/sites-available/{{ shellinabox_domain }}.conf
    owner=root
    group=root
  notify:
    - reload_nginx

- name: Activate Sites
  file:
    src: /etc/nginx/sites-available/{{ shellinabox_domain }}.conf
    dest: /etc/nginx/sites-enabled/{{ shellinabox_domain }}
    state: link
  notify: reload_nginx

- name: Enable Sites in sniproxy
  lineinfile:
    path: /etc/sniproxy.conf
    state: present
    insertafter: '## ADD ENTRIES HERE ##'
    line: '{{ shellinabox_domain }} 127.0.0.1:444'
    regexp: '^{{ shellinabox_domain }} 127.0.0.1:444'
  notify: reload_sniproxy
